int _strlen(char *s);
void error_msg(void);
int _isNum(char *num);
void rev_string(char *s);
int _putchar(char c);
char *_memcpy(char *dest, char *src, unsigned int n);
void *_realloc(void *ptr, unsigned int old_size, unsigned int new_size);
int *array_range(int min, int max);
void *_memset(void *s, int b, unsigned int n);
void *_calloc(unsigned int nmemb, unsigned int size);
char *string_nconcat(char *s1, char *s2, unsigned int n);
void *malloc_checked(unsigned int b);
